"""created roles screens

Revision ID: 0004
Revises: 0003
Create Date: 2026-04-04 23:01:26.040011

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "screen",
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_screen_id"), "screen", ["id"], unique=True)
    op.create_table(
        "role_screen",
        sa.Column("role_id", sa.String(length=255), nullable=False),
        sa.Column("screen_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["screen_id"], ["screen.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("role_id", "screen_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_screen")
    op.drop_index(op.f("ix_screen_id"), table_name="screen")
    op.drop_table("screen")
    # ### end Alembic commands ###
