"""created meetings logic

Revision ID: 0005
Revises: 0004
Create Date: 2026-04-05 01:11:06.984096

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.infra.database.entities

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | Sequence[str] | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_classes_id"), "classes", ["id"], unique=True)
    op.create_table(
        "club_year",
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_club_year_id"), "club_year", ["id"], unique=True)
    op.create_table(
        "attendance",
        sa.Column(
            "meeting_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column(
            "user_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column("attendance_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["meeting_id"], ["meetings.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "meeting_id", "user_id", name="uq_attendance_meeting_user"
        ),
    )
    op.create_index(op.f("ix_attendance_id"), "attendance", ["id"], unique=True)
    op.create_index(
        op.f("ix_attendance_meeting_id"),
        "attendance",
        ["meeting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attendance_user_id"), "attendance", ["user_id"], unique=False
    )
    op.create_table(
        "classes_requirements",
        sa.Column(
            "class_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column("section", sa.String(length=100), nullable=False),
        sa.Column("order_num", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_classes_requirements_class_id"),
        "classes_requirements",
        ["class_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_classes_requirements_id"),
        "classes_requirements",
        ["id"],
        unique=True,
    )
    op.create_table(
        "unit",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.Column(
            "class_id", app.infra.database.entities.GUID(), nullable=True
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["class_id"], ["classes.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_unit_class_id"), "unit", ["class_id"], unique=False
    )
    op.create_index(op.f("ix_unit_id"), "unit", ["id"], unique=True)
    op.create_table(
        "unit_member",
        sa.Column(
            "unit_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column(
            "user_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column("club_year_id", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["club_year_id"], ["club_year.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["unit.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("unit_id", "user_id", "club_year_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("unit_member")
    op.drop_index(op.f("ix_unit_id"), table_name="unit")
    op.drop_index(op.f("ix_unit_class_id"), table_name="unit")
    op.drop_table("unit")
    op.drop_index(
        op.f("ix_classes_requirements_id"), table_name="classes_requirements"
    )
    op.drop_index(
        op.f("ix_classes_requirements_class_id"),
        table_name="classes_requirements",
    )
    op.drop_table("classes_requirements")
    op.drop_index(op.f("ix_attendance_user_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_meeting_id"), table_name="attendance")
    op.drop_index(op.f("ix_attendance_id"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_index(op.f("ix_club_year_id"), table_name="club_year")
    op.drop_table("club_year")
    op.drop_index(op.f("ix_classes_id"), table_name="classes")
    op.drop_table("classes")
    # ### end Alembic commands ###
