"""created specialties table

Revision ID: 0006
Revises: 0005
Create Date: 2026-04-05 02:47:48.846401

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.infra.database.entities

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialties",
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_specialties_code"), "specialties", ["code"], unique=True
    )
    op.create_index(
        op.f("ix_specialties_id"), "specialties", ["id"], unique=True
    )
    op.create_table(
        "user_specialties",
        sa.Column(
            "user_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column(
            "specialty_id", app.infra.database.entities.GUID(), nullable=False
        ),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", app.infra.database.entities.GUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["specialty_id"], ["specialties.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "specialty_id", name="uq_user_specialty"
        ),
    )
    op.create_index(
        op.f("ix_user_specialties_id"), "user_specialties", ["id"], unique=True
    )
    op.create_index(
        op.f("ix_user_specialties_specialty_id"),
        "user_specialties",
        ["specialty_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_specialties_user_id"),
        "user_specialties",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_specialties_user_id"), table_name="user_specialties"
    )
    op.drop_index(
        op.f("ix_user_specialties_specialty_id"), table_name="user_specialties"
    )
    op.drop_index(op.f("ix_user_specialties_id"), table_name="user_specialties")
    op.drop_table("user_specialties")
    op.drop_index(op.f("ix_specialties_id"), table_name="specialties")
    op.drop_index(op.f("ix_specialties_code"), table_name="specialties")
    op.drop_table("specialties")
    # ### end Alembic commands ###
