"""added score tables

Revision ID: 0008
Revises: 0007
Create Date: 2026-04-05 03:45:08.233679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infra.database.entities


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_score',
    sa.Column('meeting_id', app.infra.database.entities.GUID(), nullable=False),
    sa.Column('user_id', app.infra.database.entities.GUID(), nullable=False),
    sa.Column('presenca', sa.SmallInteger(), nullable=False),
    sa.Column('pontualidade', sa.SmallInteger(), nullable=False),
    sa.Column('uniforme', sa.SmallInteger(), nullable=False),
    sa.Column('modestia', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', app.infra.database.entities.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meeting_score')
    )
    op.create_index(op.f('ix_meeting_score_id'), 'meeting_score', ['id'], unique=True)
    op.create_index(op.f('ix_meeting_score_meeting_id'), 'meeting_score', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_score_user_id'), 'meeting_score', ['user_id'], unique=False)
    op.create_table('bonus_score',
    sa.Column('user_id', app.infra.database.entities.GUID(), nullable=True),
    sa.Column('unit_id', app.infra.database.entities.GUID(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=False),
    sa.Column('semester', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', app.infra.database.entities.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_score_id'), 'bonus_score', ['id'], unique=True)
    op.create_index(op.f('ix_bonus_score_unit_id'), 'bonus_score', ['unit_id'], unique=False)
    op.create_index(op.f('ix_bonus_score_user_id'), 'bonus_score', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bonus_score_user_id'), table_name='bonus_score')
    op.drop_index(op.f('ix_bonus_score_unit_id'), table_name='bonus_score')
    op.drop_index(op.f('ix_bonus_score_id'), table_name='bonus_score')
    op.drop_table('bonus_score')
    op.drop_index(op.f('ix_meeting_score_user_id'), table_name='meeting_score')
    op.drop_index(op.f('ix_meeting_score_meeting_id'), table_name='meeting_score')
    op.drop_index(op.f('ix_meeting_score_id'), table_name='meeting_score')
    op.drop_table('meeting_score')
    # ### end Alembic commands ###
