"""added sgc column to users table

Revision ID: 0009
Revises: 0008
Create Date: 2026-04-05 03:58:42.276520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.infra.database.entities


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('codigo_sgc', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'codigo_sgc')
    # ### end Alembic commands ###
